name: CI-back - Deploy n' tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      PORT: 3001
      NODE_ENV: test
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
      DATABASE_HOST: localhost
      SECRET_KEY: "@Secret_Pantor3"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js 22
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          npm ci
          npm install sqlite3

      - name: Run tests
        run: npm run test
